/**
 * Gimmie water applicaiton
 * Gardening application
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { SensorHumidityOfDailyHumidity } from '../model/sensorHumidityOfDailyHumidity';
import { SensorHumidityOfHourlyHumidity } from '../model/sensorHumidityOfHourlyHumidity';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class HumidityControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getDailyHumidity
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDailyHumidityUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<SensorHumidityOfDailyHumidity>>;
    public getDailyHumidityUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SensorHumidityOfDailyHumidity>>>;
    public getDailyHumidityUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SensorHumidityOfDailyHumidity>>>;
    public getDailyHumidityUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SensorHumidityOfDailyHumidity>>(`${this.basePath}/sensors/humidity/daily`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getHourlyHumidity
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHourlyHumidityUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<SensorHumidityOfHourlyHumidity>>;
    public getHourlyHumidityUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SensorHumidityOfHourlyHumidity>>>;
    public getHourlyHumidityUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SensorHumidityOfHourlyHumidity>>>;
    public getHourlyHumidityUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SensorHumidityOfHourlyHumidity>>(`${this.basePath}/sensors/humidity/hourly`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
