/**
 * Gimmie water applicaiton
 * Gardening application
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Plant } from '../model/plant';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PlantControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createPlant
     *
     * @param plant plant
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPlantUsingPOST(plant: Plant, observe?: 'body', reportProgress?: boolean): Observable<Plant>;
    public createPlantUsingPOST(plant: Plant, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Plant>>;
    public createPlantUsingPOST(plant: Plant, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Plant>>;
    public createPlantUsingPOST(plant: Plant, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (plant === null || plant === undefined) {
            throw new Error('Required parameter plant was null or undefined when calling createPlantUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Plant>(`${this.basePath}/plants`,
            plant,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getPlant
     *
     * @param plantId plantId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPlantUsingGET(plantId: number, observe?: 'body', reportProgress?: boolean): Observable<Plant>;
    public getPlantUsingGET(plantId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Plant>>;
    public getPlantUsingGET(plantId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Plant>>;
    public getPlantUsingGET(plantId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (plantId === null || plantId === undefined) {
            throw new Error('Required parameter plantId was null or undefined when calling getPlantUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Plant>(`${this.basePath}/plants/${encodeURIComponent(String(plantId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getPlants
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPlantsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<Plant>>;
    public getPlantsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Plant>>>;
    public getPlantsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Plant>>>;
    public getPlantsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Plant>>(`${this.basePath}/plants`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updatePlant
     *
     * @param plant plant
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePlantUsingPUT(plant: Plant, observe?: 'body', reportProgress?: boolean): Observable<Plant>;
    public updatePlantUsingPUT(plant: Plant, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Plant>>;
    public updatePlantUsingPUT(plant: Plant, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Plant>>;
    public updatePlantUsingPUT(plant: Plant, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (plant === null || plant === undefined) {
            throw new Error('Required parameter plant was null or undefined when calling updatePlantUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Plant>(`${this.basePath}/plants/${encodeURIComponent(String(plantId))}`,
            plant,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
